name: Auto-Deploy to Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: webserver.plan-p.de
        username: philipp
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /etc/docker/projects/dsgvobanner
          git pull origin main
          docker compose down
          docker compose up -d --build
